### ISSUE TITLE
Generate a FHIR Package of definitions

### ISSUE THREAD

**Issue by Semalexa** [HealthSamurai/ig-ae#11]
#### NPM Package Specification
https://confluence.hl7.org/display/FHIR/NPM+Package+Specification

#### FHIR Packages
http://registry.fhir.org/learn

#### Creating & Publishing FHIR Packages
http://registry.fhir.org/submit

#### How to publish to FHIR Registry
https://github.com/FHIR/ig-registry

#### Example of validation against a FHIR Package:

```java -jar validator_cli.jar -version 4.0.1 resourcesToValidate/adverseEventSample.json -ig hl7.fhir.us.patient-reported-outcomes```

#### Example of published FHIR Package:

http://registry.fhir.org/package/hl7.fhir.us.patient-reported-outcomes%7C0.2.0

**Comment by Semalexa** [comment]
$ java -jar validator_cli.jar -version 4.0.1 resourcesToValidate/adverseEventSample.json -profile https://hamurai.github.io/ig-ae/StructureDefinition/astrazeneca.fhir.ig.ae-AdverseEvent -ig D:/Work/Healthsamurai/azprofiles/az-ig-package.tgz



FHIR Validation tool Version 5.1.10 (Git# efcb237d19b9). Built 2020-09-15T05:18:41.680Z (122 days old)
  Java:   14 from C:\Program Files\Java\jdk-14 on amd64 (64bit). 3028MB available
  Paths:  Current = D:\Work\Healthsamurai\az-fhir-profiles, Package Cache = C:\Users\admin\.fhir\packages
  Params: -version 4.0.1 resourcesToValidate/adverseEventSample.json -profile https://healthsamurai.github.ae/StructureDefinition/astrazeneca.fhir.ig.ae-AdverseEvent -ig D:/Work/Healthsamurai/az-fhir-profiles/az-igge.tgz
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:08.0663)
  Terminology server http://tx.fhir.org - Version 1.9.369 (00:02.0655)
  Load D:/Work/Healthsamurai/az-fhir-profiles/az-ig-package.tgz - 53 resources (00:00.0281)
  Get set...  go (00:00.0402)
Validating
  Profiles: [https://healthsamurai.github.io/ig-ae/StructureDefinition/astrazeneca.fhir.ig.ae-AdverseEvent]
  Validate resourcesToValidate/adverseEventSample.json 00:01.0046
Done. Times: Loading: 00:12.0434, validation: 00:01.0047

Success: 0 errors, 0 warnings, 1 notes
  Information @ ?? : All OK

**Comment by Semalexa** [comment]
This gives error:

$ java -jar validator_cli.jar -version 4.0.1 resourcesToValidate/adverseEventSample.json -profile https://healthsamurai.github.io/ig-ae/StructureDefinition/astrazeneca.fhir.ig.ae-AdverseEvent -ig https://github.com/HealthSamurai/ig-ae/blob/master/package/az-ig-package.tar.gz


FHIR Validation tool Version 5.1.10 (Git# efcb237d19b9). Built 2020-09-15T05:18:41.680Z (122 days old)
  Java:   14 from C:\Program Files\Java\jdk-14 on amd64 (64bit). 3028MB available
  Paths:  Current = D:\Work\Healthsamurai\az-fhir-profiles, Package Cache = C:\Users\admin\.fhir\packages
  Params: -version 4.0.1 resourcesToValidate/adverseEventSample.json -profile https://healthsamurai.github.io/ig-ae/StructureDefinition/astrazeneca.fhir.ig.ae-AdverseEvent -ig https://github.com/HealthSamurai/ig-ae/blob/master/package/az-ig-package.tar.gz
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:09.0187)
  Terminology server http://tx.fhir.org - Version 1.9.369 (00:02.0547)
  Load https://github.com/HealthSamurai/ig-ae/blob/master/package/az-ig-package.tar.gz   ..Detect format for https://github.com/HealthSamurai/ig-ae/blob/master/package/az-ig-package.tar.gz
[Fatal Error] :7:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to find/resolve/read -ig https://github.com/HealthSamurai/ig-ae/blob/master/package/az-ig-package.tar.gz
        at org.hl7.fhir.validation.ValidationEngine.fetchFromUrl(ValidationEngine.java:656)
        at org.hl7.fhir.validation.ValidationEngine.loadIgSource(ValidationEngine.java:538)
        at org.hl7.fhir.validation.ValidationEngine.loadIg(ValidationEngine.java:983)
        at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:203)
        at org.hl7.fhir.validation.Validator.main(Validator.java:186)

**Comment by Semalexa** [comment]
Problem solved: need to rename az-ig-package.tar.gz to az-ig-package.tgz.

$ java -jar validator_cli.jar -version 4.0.1 resourcesToValidate/adverseEventSample.json -profile https://healthsamurai.github.io/ig-ae/StructureDefinition/astrazeneca.fhir.ig.ae-AdverseEvent -ig https://github.com/HealthSamurai/ig-ae/blob/master/package/az-ig-package.tgz
